apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      app.kubernetes.io/component: django-ex
      app.kubernetes.io/instance: django-ex
    name: django-ex
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      app.kubernetes.io/component: django-ex
      app.kubernetes.io/instance: django-ex
    name: django-ex
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: django-ex:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/sclorg/django-ex.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.8-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 2ulu202NmTlcLzZIR1yY
      type: GitHub
    - generic:
        secret: 4uoCHmtwS-bKMXXqhMLN
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"django-ex:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"django-ex\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      app.kubernetes.io/component: django-ex
      app.kubernetes.io/instance: django-ex
    name: django-ex
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: django-ex
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: django-ex
      spec:
        containers:
        - image: ' '
          name: django-ex
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: django-ex
      app.kubernetes.io/component: django-ex
      app.kubernetes.io/instance: django-ex
    name: django-ex
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: django-ex
  status:
    loadBalancer: {}
kind: List
metadata: {}
